# Generated by Django 5.2.1 on 2025-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seller_productseller_product_seller'),
        ('orders', '0002_rename_seller_orderitem_specialist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSeller',
            new_name='ProductSpecialist',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Specialist',
        ),
        migrations.RenameField(
            model_name='productspecialist',
            old_name='seller',
            new_name='specialist',
        ),
        migrations.AlterUniqueTogether(
            name='productspecialist',
            unique_together={('product', 'specialist')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='specialist',
            field=models.ManyToManyField(blank=True, related_name='product', through='main.ProductSpecialist', to='main.specialist'),
        ),
    ]
