# Generated by Django 5.2.1 on 2025-05-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='seller',
            new_name='specialist',
        ),
    ]
